language: python
sudo: True
dist: "xenial"

python:
  - 3.7

branches:
  only:
    - master

install:
  - pip install coverage
  - pip install coveralls
  - pip install pytest
  - pip install flake8
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover
  - flake8 cmdbox

after_success:
  - coverage report
  - coveralls
